### ISSUE TITLE
feature request - offline secure connection

### ISSUE THREAD

**Issue by tim-moody** [google/key-transparency#475]
We need a way to have an encrypted connection even to uncertified servers for those trying to operate servers on a lan in areas where no internet is available.

In short, the functions of identification/authentication and secure connection need to be separated.

**Comment by gdbelvin** [comment]
If you're running offline in such a way that you can't get a TLS certificate from a public Certificate Authority, then you'll want to setup your own local Certificate Authority, and have your clients explicitly trust it.

**Comment by tim-moody** [comment]
except that browsers like chrome will complain about the cert

**Comment by tim-moody** [comment]
made worse by the growing trend for all access over https
